import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/ui/header'
import { AuthProvider } from '@/provider/auth'
import Footer from '@/components/ui/footer'
import CartProvider from '@/provider/cart'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
      <div className='flex flex-col h-full'>
      <AuthProvider>
        <CartProvider>
          <div className="flex-1">
            {children}
          </div>
          <Footer />
        </CartProvider>
        <Header /> 
      </AuthProvider>
      </div>
        </body>
    </html>
  )
}
